In [8]:
import numpy as np
from random import randrange
from datetime import datetime

In [9]:
datetime.now().strftime("%Y-%m-%d %H:%M:%S")

'2018-03-13 22:58:38'

In [10]:
scrap_freq_min = 10

In [11]:
scrapes_per_hour = (60 / scrap_freq_min)
print(scrapes_per_hour)

6.0


In [12]:
hours_scraped = 17

In [13]:
total_scrapes_per_day = hours_scraped * scrapes_per_hour
print(total_scrapes_per_day)

102.0


In [32]:
102 * 365

37230

In [14]:
listings_per_scrape = 40

In [15]:
total_per_year = total_scrapes_per_day * listings_per_scrape * 365
total_per_year

1489200.0

In [16]:
## total new listings that will appear
total_per_year * 0.01

14892.0

In [17]:
# expect ids to look like this
np.arange(40)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39])

In [18]:
102 * 0.01

1.02

In [19]:

# total new listings per year / total scrape iterations
(total_per_year * 0.01)  / (total_scrapes_per_day * 365)

0.4

In [20]:
# from above if expected 15k new listings per year from 37k scrape iterations
# then we can just 0.4 binomial chance

np.random.binomial(1, 0.4)

0

In [21]:
# to test this
scrape_iterations = int(total_scrapes_per_day * 365)
#scrape_iterations = 10
first_scrape_number = 39
for i in range(scrape_iterations):
    if np.random.binomial(1, 0.4):
        first_scrape_number += 1
    ## generate entries here
    ## i.e., np.arange(first_scrape_number-40, first_scrape_number)
print(first_scrape_number)

14915


In [22]:
# how scraped ids are generated
np.arange(first_scrape_number-40, first_scrape_number)

array([14875, 14876, 14877, 14878, 14879, 14880, 14881, 14882, 14883,
       14884, 14885, 14886, 14887, 14888, 14889, 14890, 14891, 14892,
       14893, 14894, 14895, 14896, 14897, 14898, 14899, 14900, 14901,
       14902, 14903, 14904, 14905, 14906, 14907, 14908, 14909, 14910,
       14911, 14912, 14913, 14914])

#### random entry generation

+ listing_id
+ listing_url
+ kiez
+ start_date
+ end_date (can be null)
+ scrape_time
+ stay_length_days (can be null)
+ size
+ price

In [23]:
listing_ids = np.arange(first_scrape_number-40, first_scrape_number)

In [24]:
listing_ids

array([14875, 14876, 14877, 14878, 14879, 14880, 14881, 14882, 14883,
       14884, 14885, 14886, 14887, 14888, 14889, 14890, 14891, 14892,
       14893, 14894, 14895, 14896, 14897, 14898, 14899, 14900, 14901,
       14902, 14903, 14904, 14905, 14906, 14907, 14908, 14909, 14910,
       14911, 14912, 14913, 14914])

In [25]:
random_date = datetime.now().strftime("%Y-%m-%d %H:%M:%S")

In [28]:
def generate_random_record(listing_id, scrape_time):
    listing_url = f'http://my_fake_url.com/items/{listing_id}'
    random_text = f'{randrange(8**10)}'
    return {'listing_id': listing_id,
             'listing_url': listing_url,
             'kiez': random_text,
             'start_date': random_text,
             'end_date': random_text,
             'scrape_time': scrape_time,
             'stay_length_days': np.random.randint(30, 270),
             'size': np.random.randint(10, 100),
             'price': np.random.randint(400, 1000)}
    
    
    

In [30]:
chunk = [generate_random_record(l_id, random_date) for l_id in listing_ids]

In [31]:
len(chunk)

40